### ISSUE TITLE
小白求助

### ISSUE THREAD

**Issue by singhigh** [XuefengHuang/lianjia-scrawler#5]
设置如下，数据库信息都没问题：
```
DBENGINE = 'mysql' #ENGINE OPTIONS: mysql, sqlite3, postgresql
DBNAME = 'houseinfo'
DBUSER = 'houseinfo'
DBPASSWORD = '123'
DBHOST = '127.0.0.1'
DBPORT = 3306
CITY = 'sh' # only one, shanghai=sh shenzhen=sh......
REGIONLIST = [u'pudong', u'minhang', u'baoshan', u'xuhui', u'putuo', u'yangpu', u'changning', u'songjiang', u'jiading', u'minhang', u'huangpu', u'jingan', u'zhabei', u'hongkou', u'qingpu', u'fengxian', u'jinshan', u'chongming'] # only pinyin support
```
但报如下错误：

```
root@michael-lax3:~/lianjia-scrawler# python scrawl.py 
Traceback (most recent call last):
  File "scrawl.py", line 13, in <module>
    model.database_init()
  File "/root/lianjia-scrawler/model.py", line 115, in database_init
    database.create_tables([Community, Houseinfo, Hisprice, Sellinfo, Rentinfo], safe=True)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3543, in create_tables
    create_model_tables(models, fail_silently=safe)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4869, in create_model_tables
    m.create_table(**create_table_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4561, in create_table
    db.create_table(cls)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3540, in create_table
    return self.execute_sql(*qc.create_table(model_class, safe))
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3461, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3285, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3454, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
peewee.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

```

**Comment by singhigh** [comment]
搞定，参考 http://www.cnblogs.com/littleatp/p/4612896.html 并注意字符集为utf8_general_ci
